language: java
jdk:
  - oraclejdk8

sudo: false
env:
  - TERM=dumb

before_install:
  - chmod +x gradlew deploy.sh

script:
  - ./gradlew build --stacktrace

after_success:
  - ./gradlew jacocoTestReport coveralls --stacktrace
  - bash ./deploy.sh

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
  - GH_REF: github.com/vbauer/avconv4java.git
  - secure: "Rki2d/a/sy4/C6/o5hWNX/HOFOFs6vn4IDnrs8viQoGwmbD6czmhbCVAuSchOXns1N69lNU1O3IDSksKk5Omwai0nSyOewsAlq7PoNB12TgEu5MbJOazqZnFqaPLEcyTc6Kkju1b3Qje5XNo5pspxN5ZknXD/fMsZPcFQ5+EwgY="
